apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd-st1
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: st1
  fsType: ext4
