test_pod:
  enabled: true

  image: bats/bats:1.8.2
  pullPolicy: IfNotPresent

loki:
  enabled: true
  env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP

  extraArgs:
    config.expand-env: true

  config:
    memberlist:
      bind_addr:
        - ${MY_POD_IP}
  persistence:
    enabled: true
    storageClassName: hdd-st1
    size: 125Gi
  isDefault: true
  url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
  #readinessProbe:
  # httpGet:
  #    path: /ready
  #    port: http-metrics
  #  initialDelaySeconds: 60
  #livenessProbe:
  #  httpGet:
  #    path: /ready
  #    port: http-metrics
  #  initialDelaySeconds: 60
  datasource:
    jsonData: "{}"
    uid: ""


promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://{{ .Release.Name }}:3100/loki/api/v1/push

grafana:
  enabled: true
  persistence:
    enabled: true
    storageClassName: ebs-gp3-sc
    size: 20Gi
  sidecar:
    datasources:
      label: ""
      labelValue: ""
      enabled: true
      maxLines: 1000
  image:
    tag: 8.3.5

prometheus:
  enabled: false
  isDefault: false
  url: http://{{ include "prometheus.fullname" .}}:{{ .Values.prometheus.server.service.servicePort }}{{ .Values.prometheus.server.prefixURL }}
  datasource:
    jsonData: "{}"


  outputs:
    main: |-
      output {
        loki {
          url => "http://loki:3100/loki/api/v1/push"
          #username => "test"
          #password => "test"
        }
        # stdout { codec => rubydebug }
      }

# proxy is currently only used by loki test pod
# Note: If http_proxy/https_proxy are set, then no_proxy should include the
# loki service name, so that tests are able to communicate with the loki
# service.
proxy:
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""

affinity:
    nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: role
           operator: In
           values:
             - Prod-Monitoring
